apiVersion: apps/v1 

kind: Deployment 

metadata: 
  name: challenge-ctf101-guess

spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: challenge-ctf101-guess
  template: 
    metadata: 
      labels: 
        app: challenge-ctf101-guess
    spec: 
      containers: 
      - name: challenge-ctf101-verbs
        image: tcctf2021registry.azurecr.io/ctf_guess:latest 
        imagePullPolicy: "Always"

--- 

apiVersion: v1 

kind: Service 

metadata: 
  name: challenge-ctf101-guess

spec: 
  ports: 
  - port: 80 
    targetPort: 8080
  selector: 
    app: challenge-ctf101-guess

--- 

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/ctf101/guess)$ $1/index.html permanent;
  name: challenge-ctf101-guess-ingress
  namespace: default
spec:
  tls:
  - hosts:
    - challenges.silicon-ctf.party
    secretName: tls-secret
  rules:
  - host: challenges.silicon-ctf.party
    http:
      paths:
      - backend:
          serviceName: challenge-ctf101-guess
          servicePort: 8080
        path: /ctf101/guess(/|$)(.*)
        pathType: Prefix
