apiVersion: apps/v1 

kind: Deployment 

metadata: 
  name: challenge-for300

spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: challenge-for300
  template: 
    metadata: 
      labels: 
        app: challenge-for300
    spec: 
      containers: 
      - name: challenge-for300
        image: tcctf2021registry.azurecr.io/for300:latest 
        imagePullPolicy: "Always"

--- 

apiVersion: v1 

kind: Service 

metadata: 
  name: challenge-for300

spec: 
  ports: 
  - port: 80 
    targetPort: 80
  selector: 
    app: challenge-for300 

--- 

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/for300)$ $1/index.html permanent;
  name: challenge-for300-ingress
  namespace: default
spec:
  tls:
  - hosts:
    - challenges.silicon-ctf.party
    secretName: tls-secret
  rules:
  - host: challenges.silicon-ctf.party
    http:
      paths:
      - backend:
          serviceName: challenge-for300
          servicePort: 80
        path: /for300(/|$)(.*)
        pathType: Prefix

