version: '3'
services:
    mysql-sr:
        image: tcctf2021registry.azurecr.io/web500_mysql:latest
        build: ./mysql
        container_name: mysql-server_web500
        command: --default-authentication-plugin=mysql_native_password --sql_mode=""
        restart: always
        environment:
        - MYSQL_ROOT_PASSWORD=je6H92Gagf91Ha
        - MYSQL_DATABASE=silicon
        networks:
            - backend
    web-server:
        image: tcctf2021registry.azurecr.io/web500_web:latest
        build: ./src
        # volumes:
        #     - ./src/src:/var/www/html
        ports:
            - "8234:80"
        depends_on:
            - mysql-sr
        networks:
            - backend

networks:
    backend:
        driver: bridge