apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /Users/mjackosk/Tools/kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: web-server
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /Users/mjackosk/Tools/kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: web-server
    spec:
      containers:
        - image: web-server
          name: web-server
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: web-server-claim0
      restartPolicy: Always
      volumes:
        - name: web-server-claim0
          persistentVolumeClaim:
            claimName: web-server-claim0
status: {}
