



---
apiVersion: apps/v1 

kind: Deployment 

metadata: 
  name: challenge-web400-phish

spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: challenge-web400-phish
  template: 
    metadata: 
      labels: 
        app: challenge-web400-phish
    spec: 
      containers: 
      - name: challenge-web400-phish
        image: tcctf2021registry.azurecr.io/web400_phish:latest 
        imagePullPolicy: "Always"

---
apiVersion: v1 

kind: Service 

metadata: 
  name: challenge-web400-phish

spec: 
  ports: 
  - port: 80 
    targetPort: 8080
  selector: 
    app: challenge-web400-phish

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/phisher)$ $1/index.html permanent;
  name: challenge-web400-phish-ingress
  namespace: default
spec:
  tls:
  - hosts:
    - challenges.silicon-ctf.party
    secretName: tls-secret
  rules:
  - host: challenges.silicon-ctf.party
    http:
      paths:
      - backend:
          serviceName: challenge-web400-phish
          servicePort: 8080
        path: /phisher(/|$)(.*)
        pathType: Prefix