



---
apiVersion: apps/v1 

kind: Deployment 

metadata: 
  name: challenge-web400-vault

spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: challenge-web400-vault
  template: 
    metadata: 
      labels: 
        app: challenge-web400-vault
    spec: 
      containers: 
      - name: challenge-web400-vault
        image: tcctf2021registry.azurecr.io/web400_vault:latest 
        imagePullPolicy: "Always"

---
apiVersion: v1 

kind: Service 

metadata: 
  name: challenge-web400-vault

spec: 
  ports: 
  - port: 80 
    targetPort: 80
  selector: 
    app: challenge-web400-vault

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/web400)$ $1/index.php permanent;
  name: challenge-web400-ingress
  namespace: default
spec:
  tls:
  - hosts:
    - challenges.silicon-ctf.party
    secretName: tls-secret
  rules:
  - host: challenges.silicon-ctf.party
    http:
      paths:
      - backend:
          serviceName: challenge-web400-vault
          servicePort: 80
        path: /web400(/|$)(.*)
        pathType: Prefix