version: '3'
services:
    mysql-sr-300:
        build: ./mysql
        container_name: mysql-server_web300
        command: --default-authentication-plugin=mysql_native_password --sql_mode=""
        restart: always
        environment:
        - MYSQL_ROOT_PASSWORD=je6H92Gagf91Ha
        - MYSQL_DATABASE=silicon
        networks:
            - backend
    web-server-300:
        build: ./src
        ports:
            - "8234:8080"
        depends_on:
            - mysql-sr-300
        networks:
            - backend

networks:
    backend:
        driver: bridge